// ======= DO NOT EDIT THIS FILE ============
import java.util.*;
public class Main {

   public static void main(String args[]) throws Exception {
       Scanner sc = new Scanner(System.in);
       String st; int tc;
       
       System.out.println("1. Test f1()");
       System.out.println("2. Test f2()");
     
       System.out.print("Enter TC (1 or 2): ");
       tc = sc.nextInt(); sc.nextLine();

       System.out.println("Enter a string: ");
       st = sc.nextLine();

       IString t = new MyString();
       System.out.println("OUTPUT:");
       switch(tc) {
          case 1:
             int k1 = t.f1(st);
             System.out.printf("%d\r\n",k1);
             //v1 = t.f1(st);
             //System.out.printf("%s\r\n",v1);
             //toTC1files(st, v1);
             break;
           case 2:
             String v2 = t.f2(st);
             System.out.printf("%s\r\n",v2);
             break;
         }
       System.out.println();
      sc.close();
   }
 }
